In [1]:
from commonnn import cluster
import scids
import numpy as np

In [2]:
# 2D data points (list of lists, 12 points in 2 dimensions)
data_points = np.array([   # point index
    [0, 0],       # 0
    [1, 1],       # 1
    [1, 0],       # 2
    [0, -1],      # 3
    [0.5, -0.5],  # 4
    [2,  1.5],    # 5
    [2.5, -0.5],  # 6
    [4, 2],       # 7
    [4.5, 2.5],   # 8
    [5, -1],      # 9
    [5.5, -0.5],  # 10
    [5.5, -1.5],  # 11
    [5.5, -1.7],  # 11
    [5.5, -1.8],  # 11
    [5.5, -1.9],  # 11
    [15.5, -0.5],  # 10
    [15.5, -1.5],  # 11
    [15.5, -1.7],  # 11
    [15.5, -1.8],  # 11
    [15.5, -1.9],  # 11
    [15.5, -1.73],  # 11
    [15.5, -1.81],  # 11
    [15.5, -1.91],  # 11
    ])
data_points=np.random.rand(20, 2)
max_dist = 0.3
min_neighbors = [1, 3, 4, 5, 6]
min_members = 1
max_members = 6

In [3]:
clustering = cluster.Clustering(data_points)
clustering.fit(sort_by_size=True, member_cutoff=min_members, radius_cutoff=max_dist, similarity_cutoff=min_neighbors[0], v=False)
labels = clustering.labels
labels

array([2, 2, 1, 1, 1, 1, 2, 2, 2, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1])

In [4]:
np.bincount(labels)

array([ 1, 13,  6])

In [5]:
p=scids.pointcloud.from_array(data_points)

In [6]:
l2 = p.cluster_cnn(
    max_distance=max_dist,
    min_neighbors=min_neighbors,
    min_members=min_members,
    max_members=max_members
)
l2

(20, 2)
2d
2d single instance


array([1, 1, 2, 3, 0, 0, 1, 1, 1, 0, 0, 2, 3, 0, 1, 0, 0, 2, 0, 0])

In [7]:
l2.reshape(-1)

array([1, 1, 2, 3, 0, 0, 1, 1, 1, 0, 0, 2, 3, 0, 1, 0, 0, 2, 0, 0])

In [8]:
np.bincount(l2)

array([9, 6, 3, 2])

In [ ]:
You are a computational scientist, a mathematician, and an expert software developer working in high performance computing in Python. You need to either implement or find an implementation of a clustering algorithm in Python to solve the following problem:

1. You have an energy field in 3D space, sampled on a grid of points, and available as a float numpy array of shape (nx, ny, nz). The spacing between grid points is constant in all 3D dimensions and given as a float.
2. You need to 

In [ ]:
import jax.numpy as jnp
import numpy as np

In [ ]:
a=jnp.array(np.random.rand(4,5))
a.shape

In [ ]:
a[None].shape

In [ ]:
for i in np.ndindex((1,)):
    print(i)

In [ ]:
jnp.issubdtype(type(1.), jnp.floating)

In [ ]:
int(10000) < np.inf