# Grid Generation

To create a field from any of the available methods,
you first need to specify the spatial grid
on which the field is sampled.
If you opt in to provide the modeler with binding pocket information as well
(e.g., because your field data points exceed the pocket boundaries and thus need to be masked),
then you can (and must) simply reuse the same `Grid` object 
associated with the pocket to generate a field.
Otherwise, you must manually define your grid
using one of the available functions in the `t2fpharm.grid` module, as described below.

In [1]:
import t2fpharm

## From Anchor Point, Shape, and Size

You can define a `Grid` by its shape, size,
and the coordinates of an anchor point,
using the `t2fpharm.grid.from_anchor_shape_size()` function:



In [2]:
t2fpharm.grid.from_anchor_shape_size(
    anchor=(0, 0, 0),    # Coordinates of the anchor point (in the same length unit as other data, usually Å)
    shape=(10, 20, 30),  # Shape of the grid
    size=(1, 2, 3),      # Physical size of the grid (in the same length unit as `anchor`)
    anchor_type="lower"  # Type of the anchor point; either "lower", "center", or "upper"
)

Grid(
  shape=[10 20 30],
  size=[1. 2. 3.],
  spacings=[0.11111111 0.10526316 0.10344828],
  lower_bounds=[0. 0. 0.],
  center=[0.5 1.  1.5],
  upper_bounds=[1. 2. 3.]
)

## From Anchor Point, Shape, and Spacing

You can define a `Grid` by its shape, spacing,
and the coordinates of an anchor point,
using the `t2fpharm.grid.from_anchor_shape_spacing()` function:

In [3]:
t2fpharm.grid.from_anchor_shape_spacing(
    anchor=(0, 0, 0),      
    shape=(10, 20, 30),    
    spacing=0.5,  # Spacing between grid points along main axes (in the same length unit as `anchor`)
    anchor_type="center",
)

Grid(
  shape=[10 20 30],
  size=[ 4.5  9.5 14.5],
  spacings=[0.5 0.5 0.5],
  lower_bounds=[-2.25 -4.75 -7.25],
  center=[0. 0. 0.],
  upper_bounds=[2.25 4.75 7.25]
)

## From Anchor Point, Size, and Spacing

You can define a `Grid` by its size, spacing,
and the coordinates of an anchor point,
using the `t2fpharm.grid.from_anchor_size_spacing()` function:

In [4]:
t2fpharm.grid.from_anchor_size_spacing(
    anchor=(0, 0, 0),
    size=(10, 20, 30),
    spacing=0.5,
    anchor_type="center",
)

Grid(
  shape=[21 41 61],
  size=[10. 20. 30.],
  spacings=[0.5 0.5 0.5],
  lower_bounds=[ -5. -10. -15.],
  center=[0. 0. 0.],
  upper_bounds=[ 5. 10. 15.]
)

## From Bounds and Shape

You can define a `Grid` by its bounds and shape,
using the `t2fpharm.grid.from_bounds_shape()` function:

In [5]:
t2fpharm.grid.from_bounds_shape(
    lower=(-5, -10, -15),  # Coordinates of the lower bounds (i.e. origin)
    upper=(3.5, 7.5, 10),  # Coordinates of the upper bounds
    shape=(10, 20, 30),
)

Grid(
  shape=[10 20 30],
  size=[ 8.5 17.5 25. ],
  spacings=[0.94444444 0.92105263 0.86206897],
  lower_bounds=[ -5. -10. -15.],
  center=[-0.75 -1.25 -2.5 ],
  upper_bounds=[ 3.5  7.5 10. ]
)

## From Bounds and Spacing

You can define a `Grid` by its bounds and spacing,
using the `t2fpharm.grid.from_bounds_spacing()` function:

In [6]:
grid = t2fpharm.grid.from_bounds_spacing(
    lower=(0, 0, 0),
    upper=(10, 10, 10),
    spacing=0.3,
)

grid

Grid(
  shape=[35 35 35],
  size=[10.2 10.2 10.2],
  spacings=[0.3 0.3 0.3],
  lower_bounds=[-0.1 -0.1 -0.1],
  center=[5. 5. 5.],
  upper_bounds=[10.1 10.1 10.1]
)

## Grid Methods and Attributes

Grid dimensions:

In [7]:
grid.dimension

3

Grid shape:

In [8]:
grid.shape

array([35, 35, 35])

Grid size:

In [9]:
grid.size

array([10.2, 10.2, 10.2])

Grid spacings:

In [10]:
grid.spacings

array([0.3, 0.3, 0.3])

Grid unit vectors:

In [11]:
grid.unit_vectors

Array([[0.3, 0. , 0. ],
       [0. , 0.3, 0. ],
       [0. , 0. , 0.3]], dtype=float64)

Total number of grid points:

In [12]:
grid.point_count

np.int64(42875)

Volume of a grid point:

In [13]:
grid.point_volume

np.float64(0.027)

Center coordinates:

In [14]:
grid.center

array([5., 5., 5.])

Coordinates of the lower bound (origin):

In [15]:
grid.lower_bounds

array([-0.1, -0.1, -0.1])

Coordinates of the upper bound:

In [16]:
grid.upper_bounds

array([10.1, 10.1, 10.1])

Coordinates of all grid points in the same shape as the grid itself:

In [17]:
grid.coordinates.shape

(35, 35, 35, 3)

Coordinates of all grid points as a flat 2D array:

In [18]:
grid.coordinates_2d.shape

(42875, 3)

Indices of all grid points in the same shape as the grid itself:

In [19]:
grid.indices.shape

(35, 35, 35, 3)

Unique distances between all grid points, sorted from smallest to largest:

In [20]:
grid.unique_distances

array([ 0.3       ,  0.42426407,  0.51961524, ..., 17.32743489,
       17.49542797, 17.66691824], shape=(2164,))

For a set of given coordinates, find the index of the nearest grid point to each given coordinates,
their distance, and whether the coordinates lie inside the grid:

In [21]:
indices, distances, is_inside = grid.nearest_point([[1, 0.5, 0.5], [20, 20, 20]])
print(f"indices: {indices}", f"distances: {distances}", f"is inside: {is_inside}", sep="\n")

indices: [[ 4  2  2]
 [34 34 34]]
distances: [ 0.1        17.14730299]
is inside: [ True False]


Get coordinates of grid points given their indices:

In [22]:
grid.index_coordinates([[0,0,0], [3,4,5]])

array([[-0.1, -0.1, -0.1],
       [ 0.8,  1.1,  1.4]])

Calculate the number of common neighbors for two grid points within a radius:

In [23]:
grid.common_neighbors_count(neighborhood_radius=1.5, point1=(0,0,0), point2=(0,0,1))

93

Create a spherical footprint (a.k.a. structuring element) with a given radius:

In [24]:
grid.footprint_spherical(radius=0.6)

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False,  True,  True,  True, False],
        [False,  True,  True,  True, False],
        [False,  True,  True,  True, False],
        [False, False, False, False, False]],

       [[False, False,  True, False, False],
        [False,  True,  True,  True, False],
        [ True,  True,  True,  True,  True],
        [False,  True,  True,  True, False],
        [False, False,  True, False, False]],

       [[False, False, False, False, False],
        [False,  True,  True,  True, False],
        [False,  True,  True,  True, False],
        [False,  True,  True,  True, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
  

Get direction vectors in the grid:

In [25]:
grid.direction_vectors()

array([[-1, -1, -1],
       [-1, -1,  0],
       [-1, -1,  1],
       [-1,  0, -1],
       [-1,  0,  0],
       [-1,  0,  1],
       [-1,  1, -1],
       [-1,  1,  0],
       [-1,  1,  1],
       [ 0, -1, -1],
       [ 0, -1,  0],
       [ 0, -1,  1],
       [ 0,  0, -1],
       [ 0,  0,  1],
       [ 0,  1, -1],
       [ 0,  1,  0],
       [ 0,  1,  1],
       [ 1, -1, -1],
       [ 1, -1,  0],
       [ 1, -1,  1],
       [ 1,  0, -1],
       [ 1,  0,  0],
       [ 1,  0,  1],
       [ 1,  1, -1],
       [ 1,  1,  0],
       [ 1,  1,  1]])

Convert the grid to a dictionary, which can be saved and used to recreate the grid:

In [26]:
grid_data = grid.to_dict()
grid_data

{'shape': [35, 35, 35],
 'size': [10.2, 10.2, 10.2],
 'spacing': [0.3, 0.3, 0.3],
 'lower': [-0.09999999999999981, -0.09999999999999981, -0.09999999999999981],
 'upper': [10.1, 10.1, 10.1]}

In [27]:
grid_recreated = t2fpharm.grid.from_data(**grid_data)

Check for equality between two grids:

In [28]:
grid == grid_recreated

True