# Quickstart Guide

All functionalities are accessible from the top-level `t2fpharm` package,
which is the only module you need to import:

In [1]:
import t2fpharm

A T<sup>2</sup>F pharmacophore modeler can then be created using the `t2fpharm.modeler()` function:

In [2]:
help(t2fpharm.modeler)

Help on function modeler in module t2fpharm:

modeler(field: scids.field.Field, pocket: caddpy.pocket.pocket.Pocket | None = None, receptor: caddpy.chemsys.ChemicalSystem | None = None) -> t2fpharm.modeler.Modeler
    Create a target-focused pharmacophore modeler.

    Parameters
    ----------
    field
        Field containing energy values or other metrics
        corresponding to pharmacophore features.
    pocket
        Optional pocket mask for the field.
    receptor
        Receptor associated with the pharmacophore modeler.



To create a new modeler,
at the very least you need a set of 3D scalar fields,
each measuring some metric for the favorability of a pharamacophore feature
at different points within the binding pocket of a receptor.
The modeler then provides various methods
to extract pharmacophore features from the corresponding field values.
If the fields do not already contain information about the binding pocket,
you may also optionally provide pocket information so that only those
field datapoints that lie within the pocket are considered for pharmacophore generation.
Moreover, you may optionally provide the receptor itself as well,
which can then be used in post-analysis steps, e.g., for visualization.
Each of these inputs must be provided as a special object,
which can be created from various inputs as explained below.

## Grid Generation

To create a field from any of the available methods,
you first need to specify the spatial grid
on which the field is sampled.
If you opt in to provide the modeler with binding pocket information as well
(e.g., because your field data points exceed the pocket boundaries and thus need to be masked),
then you can (and must) simply reuse the same `Grid` object associated with the pocket to generate a field (see section Pocket Generation).
Otherwise, you must manually define your grid using one of the available functions in the `t2fpharm.grid` module, as described below.

### From Anchor Point, Shape, and Size

You can define a `Grid` by its shape, size,
and the coordinates of an anchor point,
using the `t2fpharm.grid.from_anchor_shape_size()` function:



In [3]:
help(t2fpharm.grid.from_anchor_shape_size)

Help on function from_anchor_shape_size in module scids.grid:

from_anchor_shape_size(anchor: 'Sequence[float]', shape: 'Sequence[int] | int', size: 'Sequence[float] | float', *, anchor_type: "Literal['lower', 'center', 'upper'] | Sequence[int]" = 'lower')
    Create a `Grid` from an anchor point, shape, and size.

    Parameters
    ----------
    anchor
        Coordinates of the anchor point of the grid.
        The type of anchor point is determined by `anchor_type`.
    shape
        Shape of the grid, i.e. number of points in each dimension.
        If a scalar is provided, it is expanded to a 1D array
        of the same size as the grid dimension.
        Otherwise, it must be a 1D array of the same size as `anchor`.
    size
        Physical length of the grid in each dimension.
        If a scalar is provided, it is expanded to a 1D array
        of the same size as the grid dimension.
        Otherwise, it must be a 1D array of the same size as `anchor`.
    anchor_type
    

For example:

In [4]:
t2fpharm.grid.from_anchor_shape_size(
    anchor=(0, 0, 0),
    shape=(10, 20, 30),
    size=(1, 2, 3),
)

Grid(
  shape=[10 20 30],
  size=[1. 2. 3.],
  spacings=[0.11111111 0.10526316 0.10344828],
  lower_bounds=[0. 0. 0.],
  center=[0.5 1.  1.5],
  upper_bounds=[1. 2. 3.]
)

### From Anchor Point, Shape, and Spacing

You can define a `Grid` by its shape, spacing,
and the coordinates of an anchor point,
using the `t2fpharm.grid.from_anchor_shape_spacing()` function:

In [5]:
help(t2fpharm.grid.from_anchor_shape_spacing)

Help on function from_anchor_shape_spacing in module scids.grid:

from_anchor_shape_spacing(anchor: 'Sequence[float]', shape: 'Sequence[int] | int', spacing: 'Sequence[float] | float', *, anchor_type: "Literal['lower', 'center', 'upper'] | Sequence[int]" = 'lower')
    Create a `Grid` from an anchor point, shape, and nominal spacings.

    Parameters
    ----------
    anchor
        Coordinates of the anchor point of the grid.
        The type of anchor point is determined by `anchor_type`.
    shape
        Shape of the grid, i.e. number of points in each dimension.
        If a scalar is provided, it is expanded to a 1D array
        of the same size as the grid dimension.
        Otherwise, it must be a 1D array of the same size as `anchor`.
    spacing
        Spacing between grid points in each dimension.
        If a scalar is provided, it is expanded to a 1D array
        of the same size as the grid dimension.
        Otherwise, it must be a 1D array of the same size as `ancho

For example:

In [6]:
t2fpharm.grid.from_anchor_shape_spacing(
    anchor=(0, 0, 0),
    shape=(10, 20, 30),
    spacing=0.5,
)

Grid(
  shape=[10 20 30],
  size=[ 4.5  9.5 14.5],
  spacings=[0.5 0.5 0.5],
  lower_bounds=[0. 0. 0.],
  center=[2.25 4.75 7.25],
  upper_bounds=[ 4.5  9.5 14.5]
)

### From Anchor Point, Size, and Spacing

You can define a `Grid` by its size, spacing,
and the coordinates of an anchor point,
using the `t2fpharm.grid.from_anchor_size_spacing()` function:

In [7]:
help(t2fpharm.grid.from_anchor_size_spacing)

Help on function from_anchor_size_spacing in module scids.grid:

from_anchor_size_spacing(anchor: 'Sequence[float]', size: 'Sequence[float] | float', spacing: 'Sequence[float] | float', *, anchor_type: "Literal['lower', 'center', 'upper'] | Sequence[int]" = 'lower', shrink_to_fit: 'bool' = False)
    Create a `Grid` from an anchor point, size, and nominal spacings.

    Parameters
    ----------
    anchor
        Coordinates of the anchor point of the grid.
        The type of anchor point is determined by `anchor_type`.
    size
        Physical length of the grid in each dimension.
        If a scalar is provided, it is expanded to a 1D array
        of the same size as the grid dimension.
        Otherwise, it must be a 1D array of the same size as `anchor`.
    spacing
        Spacing between grid points in each dimension.
        If a scalar is provided, it is expanded to a 1D array
        of the same size as the grid dimension.
        Otherwise, it must be a 1D array of the sa

For example:

In [8]:
t2fpharm.grid.from_anchor_size_spacing(
    anchor=(0, 0, 0),
    size=(10, 20, 30),
    spacing=(0.5, 1, 1.5),
    anchor_type="center",
)

Grid(
  shape=[21 21 21],
  size=[10. 20. 30.],
  spacings=[0.5 1.  1.5],
  lower_bounds=[ -5. -10. -15.],
  center=[0. 0. 0.],
  upper_bounds=[ 5. 10. 15.]
)

### From Bounds and Shape

You can define a `Grid` by its bounds and shape,
using the `t2fpharm.grid.from_bounds_shape()` function:

In [9]:
help(t2fpharm.grid.from_bounds_shape)

Help on function from_bounds_shape in module scids.grid:

from_bounds_shape(lower: 'Sequence[float]', upper: 'Sequence[float]', shape: 'Sequence[int] | int') -> 'Grid'
    Create a `Grid` from its bounds and shape.

    Note that `lower` and `upper` must be 1D arrays of the same size,
    where the size is the number of dimensions of the grid.
    For example for 3D grids, arguments must be 1D arrays of length 3,
    corresponding to the x, y, and z axes, respectively.

    Parameters
    ----------
    lower
        Coordinates of the point with minimum index values in all dimensions.
    upper
        Coordinates of the point with maximum index values in all dimensions.
    shape
        Shape of the grid, i.e. number of points in each dimension.
        If a scalar is provided, it is expanded to a 1D array
        of the same size as the grid dimension.
        Otherwise, it must be a 1D array of the same size as `lower` and `upper`.



For example:

In [10]:
t2fpharm.grid.from_bounds_shape(
    lower=(-5, -10, -15),
    upper=(3.5, 7.5, 10),
    shape=(10, 20, 30),
)

Grid(
  shape=[10 20 30],
  size=[ 8.5 17.5 25. ],
  spacings=[0.94444444 0.92105263 0.86206897],
  lower_bounds=[ -5. -10. -15.],
  center=[-0.75 -1.25 -2.5 ],
  upper_bounds=[ 3.5  7.5 10. ]
)

### From Bounds and Spacing

You can define a `Grid` by its bounds and spacing,
using the `t2fpharm.grid.from_bounds_spacing()` function:

In [11]:
help(t2fpharm.grid.from_bounds_spacing)

Help on function from_bounds_spacing in module scids.grid:

from_bounds_spacing(lower: 'Sequence[float]', upper: 'Sequence[float]', spacing: 'Sequence[float] | float', *, wiggle: "Literal['bounds', 'lower', 'upper', 'spacing']" = 'bounds', shrink_to_fit: 'bool' = False) -> 'Grid'
    Create a `Grid` from its bounds and nominal spacings.

    Note that `lower` and `upper` must be 1D arrays of the same size,
    where the size is the number of dimensions of the grid.
    For example for 3D grids, arguments must be 1D arrays of length 3,
    corresponding to the x, y, and z axes, respectively.

    Parameters
    ----------
    lower
        Coordinates of the point with minimum values in all dimensions.
    upper
        Coordinates of the point with maximum values in all dimensions.
    spacing
        Spacing between grid points in each dimension.
        If a scalar is provided, it is expanded to a 1D array
        of the same size as the grid dimension.
        Otherwise, it must be 

For example:

In [12]:
t2fpharm.grid.from_bounds_spacing(
    lower=(0, 0, 0),
    upper=(10, 10, 10),
    spacing=0.3,
)

Grid(
  shape=[35 35 35],
  size=[10.2 10.2 10.2],
  spacings=[0.3 0.3 0.3],
  lower_bounds=[-0.1 -0.1 -0.1],
  center=[5. 5. 5.],
  upper_bounds=[10.1 10.1 10.1]
)

## Field Generation

### From Pre-Computed Data

The shortest and most flexible way to create a `Field` object
is by providing your own pre-computed field data to the `t2fpharm.field.from_data()` function:

In [13]:
help(t2fpharm.field.from_data)

Help on function from_data in module t2fpharm.field:

from_data(grid: 'Grid', tensor: 'ArrayLike', feature_ids: 'Sequence[str]', dtype: 'DTypeLike | None' = None) -> 'Field'
    Create a field from pre-computed data.

    Parameters
    ----------
    grid
        Grid defining the spatial structure of the field.
    tensor
        N-dimensional `(N >= 4)` array-like object
        (e.g., list, NumPy array, JAX array)
        containing the field data.
        The first dimension of the array
        must correspond to different features
        whose IDs are provided in `feature_ids`.
        The last three dimensions of the array
        must match the shape of the grid.
        All other dimensions are considered batch dimensions
        corresponding to different instances of the field
        (e.g., for different receptor conformations).
    feature_ids
        Labels for the pharmacophore features
        the tensor values correspond to.
        This should be a sequence of strin

For example:

In [14]:
import numpy as np

# Dummy field data for 5 feature metrics,
# each sampled on a 20x30x40 grid:
feature_ids = ["f1", "f2", "f3", "f4", "f5"]
field_data = np.random.rand(len(feature_ids), 20, 30, 40)

# Suppose the field's grid center is at (15.5, 16, 17.5)
# and grid spacing is 0.3 in all three dimensions:
field_grid = t2fpharm.grid.from_anchor_shape_spacing(
    anchor=(15.5, 16, 17.5),
    shape=field_data.shape[1:],
    spacing=0.3,
    anchor_type="center",
)

t2fpharm.field.from_data(
    grid=field_grid,
    tensor=field_data,
    feature_ids=feature_ids,
)

Field(
  grid=Grid(
    shape=[20 30 40],
    size=[ 5.7  8.7 11.7],
    spacings=[0.3 0.3 0.3],
    lower_bounds=[12.65 11.65 11.65],
    center=[15.5 16.  17.5],
    upper_bounds=[18.35 20.35 23.35]
  ),
  tensor=array(
    [[[[0.081 0.917 0.606 ... 0.344 0.668 0.353]
       [0.7   0.363 0.21  ... 0.865 0.137 0.112]
       [0.672 0.596 0.008 ... 0.893 0.923 0.363]
       ...
       [0.831 0.504 0.926 ... 0.193 0.797 0.372]
       [0.512 0.385 0.535 ... 0.332 0.681 0.535]
       [0.781 0.125 0.112 ... 0.385 0.237 0.167]]

      [[0.39  0.512 0.913 ... 0.849 0.438 0.779]
       [0.601 0.337 0.755 ... 0.305 0.78  0.277]
       [0.804 0.231 0.164 ... 0.817 0.483 0.112]
       ...
       [0.083 0.665 0.912 ... 0.16  0.022 0.414]
       [0.934 0.299 0.644 ... 0.719 0.931 0.217]
       [0.42  0.429 0.295 ... 0.989 0.375 0.799]]

      [[0.571 0.021 0.161 ... 0.759 0.675 0.65 ]
       [0.255 0.632 0.821 ... 0.497 0.322 0.136]
       [0.555 0.791 0.45  ... 0.182 0.11  0.908]
       ...
      

### From AutoGrid